
        require "croupier"
        require "tablo"
        require "../src/sheety/functions/registry"

        # Auto-generated Excel formula tasks for Croupier
        # Generated by Sheety

      
# Set initial cell values
Croupier::TaskManager.set("Sheet1!A1", "100.0")
Croupier::TaskManager.set("Sheet1!A2", "200.0")
Croupier::TaskManager.set("Sheet1!A3", "300.0")
Croupier::TaskManager.set("Sheet1!B1", "Hello")
Croupier::TaskManager.set("Sheet1!B2", "World")
Croupier::TaskManager.set("Sheet1!C1", "5.0")
Croupier::TaskManager.set("Sheet1!C2", "3.0")
Croupier::TaskManager.set("Sheet2!A1", "100.0")



        Croupier::Task.new(
          id: "formula_Sheet1_A4",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3"],
          outputs: ["kv://Sheet1!A4"],
        ) do
          begin
            result = (Sheety::Functions.sum([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_A5",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3"],
          outputs: ["kv://Sheet1!A5"],
        ) do
          begin
            result = (Sheety::Functions.average([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_B3",
          inputs: ["kv://Sheet1!B1", "kv://Sheet1!B2"],
          outputs: ["kv://Sheet1!B3"],
        ) do
          begin
            result = (Sheety::Functions.concat([(Croupier::TaskManager.get("Sheet1!B1") || ""), " ", (Croupier::TaskManager.get("Sheet1!B2") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_C3",
          inputs: ["kv://Sheet1!C1", "kv://Sheet1!C2"],
          outputs: ["kv://Sheet1!C3"],
        ) do
          begin
            result = (Sheety::Functions.if(Sheety::Functions.gt((Croupier::TaskManager.get("Sheet1!C1") || ""), (Croupier::TaskManager.get("Sheet1!C2") || "")), "Yes", "No"))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D1",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3"],
          outputs: ["kv://Sheet1!D1"],
        ) do
          begin
            result = (Sheety::Functions.max([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D2",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3"],
          outputs: ["kv://Sheet1!D2"],
        ) do
          begin
            result = (Sheety::Functions.min([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet2_A2",
          inputs: ["kv://Sheet1!A4"],
          outputs: ["kv://Sheet2!A2"],
        ) do
          begin
            result = (begin; ln = Sheety::Functions.to_float((Croupier::TaskManager.get("Sheet1!A4") || "")); rn = Sheety::Functions.to_float(2.0); (ln && rn) ? (ln * rn).to_s : nil; end)

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet2_A3",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2"],
          outputs: ["kv://Sheet2!A3"],
        ) do
          begin
            result = (Sheety::Functions.sum([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


# Helper functions

# Helper function to convert column number to letters
def col_num_to_letter(num)
  result = ""
  while num > 0
    num -= 1
    result = ('A' + (num % 26)).to_s + result
    num //= 26
  end
  result
end

def print_sheet(data, sheet_name)
  # Find the grid dimensions
  max_col = 0
  max_row = 0

  data.each do |cell|
    if match = cell[:cell].match(/^([A-Z]+)(\d+)$/)
      col = match[1]
      row = match[2].to_i

      # Convert column to number for comparison
      col_num = 0
      col.each_char { |c| col_num = col_num * 26 + (c.ord - 'A'.ord + 1) }

      max_col = col_num if col_num > max_col
      max_row = row if row > max_row
    end
  end

  # Create a 2D grid
  grid = Array.new(max_row) { Array.new(max_col, "") }

  # Fill the grid
  data.each do |cell|
    if match = cell[:cell].match(/^([A-Z]+)(\d+)$/)
      col = match[1]
      row = match[2].to_i - 1  # Convert to 0-indexed

      # Convert column to number
      col_num = 0
      col.each_char { |c| col_num = col_num * 26 + (c.ord - 'A'.ord + 1) }

      value = cell[:value]
      formula = cell[:formula]

      # Display: if there's a formula, show it, otherwise just the value
      display = formula.empty? ? value : formula + " -> " + value

      grid[row][col_num - 1] = display
    end
  end

  # Build column headers (A, B, C, ...)
  column_headers = (1..max_col).map { |i| col_num_to_letter(i) }

  # Build table data with row numbers
  table_data = (0...max_row).map do |row_idx|
    [row_idx + 1] + grid[row_idx]
  end

  # Create and print the table using Tablo
  table = Tablo::Table.new(table_data) do |t|
    t.add_column("Row", &.[](0).to_s)
    (1..max_col).each do |col_idx|
      t.add_column(column_headers[col_idx - 1], &.[](col_idx).to_s)
    end
  end

  puts table
  puts ""
end


# Initial run
puts "=== Executing Croupier Tasks ==="
Croupier::TaskManager.run_tasks

# Display results
refresh_display

# Interactive REPL
puts ""
puts "=== Interactive Mode ==="
puts "Enter cell assignments (e.g., A1=123, Sheet2!B5=hello)"
puts "Commands: 'quit' or 'exit' to quit, 'show' to refresh display"
puts ""

loop do
  print "> "
  input = gets

  break if input.nil? || input.blank?

  input = input.strip

  # Check for commands
  case input
  when "quit", "exit"
    puts "Goodbye!"
    break
  when "show", "refresh"
    refresh_display
    next
  end

  # Parse cell assignment
  if match = input.match(/^([A-Za-z0-9!]+)=(.*)$/)
    cell_ref = match[1]
    value = match[2]

    # Add sheet prefix if not present (default to Sheet1)
    full_ref = cell_ref.includes?("!") ? cell_ref : "Sheet1!" + cell_ref

    # Try to parse as number, otherwise treat as string
    parsed_value = begin
      if value.includes?(".")
        value.to_f
      else
        value.to_i
      end
    rescue
      value
    end

    # Set the value
    Croupier::TaskManager.set(full_ref, parsed_value.to_s)
    puts "Set " + full_ref + " = " + parsed_value.to_s

    # Run affected tasks
    Croupier::TaskManager.run_tasks

    # Refresh display
    refresh_display
  else
    puts "Invalid format. Use: CELL=VALUE (e.g., A1=123, B2=hello)"
  end
end

def refresh_display
  # Collect current cell data
    sheet_Sheet1_data = [
            {cell: "A4", formula: "=SUM(A1:A3)", value: Croupier::TaskManager.get("Sheet1!A4") || "(empty)"},
          {cell: "A5", formula: "=AVERAGE(A1:A3)", value: Croupier::TaskManager.get("Sheet1!A5") || "(empty)"},
          {cell: "B3", formula: "=CONCAT(B1,\" \",B2)", value: Croupier::TaskManager.get("Sheet1!B3") || "(empty)"},
          {cell: "C3", formula: "=IF(C1>C2,\"Yes\",\"No\")", value: Croupier::TaskManager.get("Sheet1!C3") || "(empty)"},
          {cell: "D1", formula: "=MAX(A1:A3)", value: Croupier::TaskManager.get("Sheet1!D1") || "(empty)"},
          {cell: "D2", formula: "=MIN(A1:A3)", value: Croupier::TaskManager.get("Sheet1!D2") || "(empty)"},
          {cell: "A1", formula: "", value: Croupier::TaskManager.get("Sheet1!A1") || "(empty)"},
          {cell: "A2", formula: "", value: Croupier::TaskManager.get("Sheet1!A2") || "(empty)"},
          {cell: "A3", formula: "", value: Croupier::TaskManager.get("Sheet1!A3") || "(empty)"},
          {cell: "B1", formula: "", value: Croupier::TaskManager.get("Sheet1!B1") || "(empty)"},
          {cell: "B2", formula: "", value: Croupier::TaskManager.get("Sheet1!B2") || "(empty)"},
          {cell: "C1", formula: "", value: Croupier::TaskManager.get("Sheet1!C1") || "(empty)"},
          {cell: "C2", formula: "", value: Croupier::TaskManager.get("Sheet1!C2") || "(empty)"}
          ]

  sheet_Sheet2_data = [
            {cell: "A2", formula: "=Sheet1!A4*2", value: Croupier::TaskManager.get("Sheet2!A2") || "(empty)"},
          {cell: "A3", formula: "=SUM(Sheet1!A1:A2)", value: Croupier::TaskManager.get("Sheet2!A3") || "(empty)"},
          {cell: "A1", formula: "", value: Croupier::TaskManager.get("Sheet2!A1") || "(empty)"}
          ]

  # Print all sheets
  puts ""
  puts "=== Spreadsheet Results ==="
  puts ""

    print_sheet(sheet_Sheet1_data, "Sheet1")
  print_sheet(sheet_Sheet2_data, "Sheet2")
end
