
          require "croupier"
          require "termisu"
          require "../src/sheety/tui"
          require "../src/sheety/functions/registry"

          # Auto-generated Excel formula tasks for Croupier
          # Generated by Sheety

        
# Set initial cell values
Croupier::TaskManager.set("Sheet1!A1", "100.0")
Croupier::TaskManager.set("Sheet1!A2", "200.0")
Croupier::TaskManager.set("Sheet1!A3", "300.0")
Croupier::TaskManager.set("Sheet1!A4", "150.0")
Croupier::TaskManager.set("Sheet1!B1", "Hello")
Croupier::TaskManager.set("Sheet1!B2", "World")
Croupier::TaskManager.set("Sheet1!C1", "5.0")
Croupier::TaskManager.set("Sheet1!C2", "3.0")
Croupier::TaskManager.set("Sheet2!A1", "100.0")
Croupier::TaskManager.set("Sheet1!A5", "")
Croupier::TaskManager.set("Sheet1!A6", "")
Croupier::TaskManager.set("Sheet1!A7", "")
Croupier::TaskManager.set("Sheet1!A8", "")
Croupier::TaskManager.set("Sheet1!A9", "")
Croupier::TaskManager.set("Sheet1!A10", "")
Croupier::TaskManager.set("Sheet1!A11", "")
Croupier::TaskManager.set("Sheet1!A12", "")
Croupier::TaskManager.set("Sheet1!A13", "")
Croupier::TaskManager.set("Sheet1!A14", "")
Croupier::TaskManager.set("Sheet1!A15", "")
Croupier::TaskManager.set("Sheet1!A16", "")
Croupier::TaskManager.set("Sheet1!A17", "")
Croupier::TaskManager.set("Sheet1!A18", "")
Croupier::TaskManager.set("Sheet1!A19", "")
Croupier::TaskManager.set("Sheet1!A20", "")
Croupier::TaskManager.set("Sheet1!D3", "")



        Croupier::Task.new(
          id: "formula_Sheet1_B3",
          inputs: ["kv://Sheet1!B1", "kv://Sheet1!B2"],
          outputs: ["kv://Sheet1!B3"],
        ) do
          begin
            result = (Sheety::Functions.concat([(Croupier::TaskManager.get("Sheet1!B1") || ""), " ", (Croupier::TaskManager.get("Sheet1!B2") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_C3",
          inputs: ["kv://Sheet1!C1", "kv://Sheet1!C2"],
          outputs: ["kv://Sheet1!C3"],
        ) do
          begin
            result = (Sheety::Functions.if(Sheety::Functions.gt((Croupier::TaskManager.get("Sheet1!C1") || ""), (Croupier::TaskManager.get("Sheet1!C2") || "")), "Yes", "No"))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D1",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3", "kv://Sheet1!A4", "kv://Sheet1!A5", "kv://Sheet1!A6", "kv://Sheet1!A7", "kv://Sheet1!A8", "kv://Sheet1!A9", "kv://Sheet1!A10", "kv://Sheet1!A11", "kv://Sheet1!A12", "kv://Sheet1!A13", "kv://Sheet1!A14", "kv://Sheet1!A15", "kv://Sheet1!A16", "kv://Sheet1!A17", "kv://Sheet1!A18", "kv://Sheet1!A19", "kv://Sheet1!A20"],
          outputs: ["kv://Sheet1!D1"],
        ) do
          begin
            result = (Sheety::Functions.max([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || ""), (Croupier::TaskManager.get("Sheet1!A4") || ""), (Croupier::TaskManager.get("Sheet1!A5") || ""), (Croupier::TaskManager.get("Sheet1!A6") || ""), (Croupier::TaskManager.get("Sheet1!A7") || ""), (Croupier::TaskManager.get("Sheet1!A8") || ""), (Croupier::TaskManager.get("Sheet1!A9") || ""), (Croupier::TaskManager.get("Sheet1!A10") || ""), (Croupier::TaskManager.get("Sheet1!A11") || ""), (Croupier::TaskManager.get("Sheet1!A12") || ""), (Croupier::TaskManager.get("Sheet1!A13") || ""), (Croupier::TaskManager.get("Sheet1!A14") || ""), (Croupier::TaskManager.get("Sheet1!A15") || ""), (Croupier::TaskManager.get("Sheet1!A16") || ""), (Croupier::TaskManager.get("Sheet1!A17") || ""), (Croupier::TaskManager.get("Sheet1!A18") || ""), (Croupier::TaskManager.get("Sheet1!A19") || ""), (Croupier::TaskManager.get("Sheet1!A20") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D2",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3", "kv://Sheet1!A4", "kv://Sheet1!A5", "kv://Sheet1!A6", "kv://Sheet1!A7", "kv://Sheet1!A8", "kv://Sheet1!A9", "kv://Sheet1!A10", "kv://Sheet1!A11", "kv://Sheet1!A12", "kv://Sheet1!A13", "kv://Sheet1!A14", "kv://Sheet1!A15", "kv://Sheet1!A16", "kv://Sheet1!A17", "kv://Sheet1!A18", "kv://Sheet1!A19", "kv://Sheet1!A20"],
          outputs: ["kv://Sheet1!D2"],
        ) do
          begin
            result = (Sheety::Functions.min([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || ""), (Croupier::TaskManager.get("Sheet1!A4") || ""), (Croupier::TaskManager.get("Sheet1!A5") || ""), (Croupier::TaskManager.get("Sheet1!A6") || ""), (Croupier::TaskManager.get("Sheet1!A7") || ""), (Croupier::TaskManager.get("Sheet1!A8") || ""), (Croupier::TaskManager.get("Sheet1!A9") || ""), (Croupier::TaskManager.get("Sheet1!A10") || ""), (Croupier::TaskManager.get("Sheet1!A11") || ""), (Croupier::TaskManager.get("Sheet1!A12") || ""), (Croupier::TaskManager.get("Sheet1!A13") || ""), (Croupier::TaskManager.get("Sheet1!A14") || ""), (Croupier::TaskManager.get("Sheet1!A15") || ""), (Croupier::TaskManager.get("Sheet1!A16") || ""), (Croupier::TaskManager.get("Sheet1!A17") || ""), (Croupier::TaskManager.get("Sheet1!A18") || ""), (Croupier::TaskManager.get("Sheet1!A19") || ""), (Croupier::TaskManager.get("Sheet1!A20") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D3",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3", "kv://Sheet1!A4", "kv://Sheet1!A5", "kv://Sheet1!A6", "kv://Sheet1!A7", "kv://Sheet1!A8", "kv://Sheet1!A9", "kv://Sheet1!A10", "kv://Sheet1!A11", "kv://Sheet1!A12", "kv://Sheet1!A13", "kv://Sheet1!A14", "kv://Sheet1!A15", "kv://Sheet1!A16", "kv://Sheet1!A17", "kv://Sheet1!A18", "kv://Sheet1!A19", "kv://Sheet1!A20"],
          outputs: ["kv://Sheet1!D3"],
        ) do
          begin
            result = (Sheety::Functions.sum([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || ""), (Croupier::TaskManager.get("Sheet1!A4") || ""), (Croupier::TaskManager.get("Sheet1!A5") || ""), (Croupier::TaskManager.get("Sheet1!A6") || ""), (Croupier::TaskManager.get("Sheet1!A7") || ""), (Croupier::TaskManager.get("Sheet1!A8") || ""), (Croupier::TaskManager.get("Sheet1!A9") || ""), (Croupier::TaskManager.get("Sheet1!A10") || ""), (Croupier::TaskManager.get("Sheet1!A11") || ""), (Croupier::TaskManager.get("Sheet1!A12") || ""), (Croupier::TaskManager.get("Sheet1!A13") || ""), (Croupier::TaskManager.get("Sheet1!A14") || ""), (Croupier::TaskManager.get("Sheet1!A15") || ""), (Croupier::TaskManager.get("Sheet1!A16") || ""), (Croupier::TaskManager.get("Sheet1!A17") || ""), (Croupier::TaskManager.get("Sheet1!A18") || ""), (Croupier::TaskManager.get("Sheet1!A19") || ""), (Croupier::TaskManager.get("Sheet1!A20") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet1_D4",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2", "kv://Sheet1!A3", "kv://Sheet1!A4", "kv://Sheet1!A5", "kv://Sheet1!A6", "kv://Sheet1!A7", "kv://Sheet1!A8", "kv://Sheet1!A9", "kv://Sheet1!A10", "kv://Sheet1!A11", "kv://Sheet1!A12", "kv://Sheet1!A13", "kv://Sheet1!A14", "kv://Sheet1!A15", "kv://Sheet1!A16", "kv://Sheet1!A17", "kv://Sheet1!A18", "kv://Sheet1!A19", "kv://Sheet1!A20"],
          outputs: ["kv://Sheet1!D4"],
        ) do
          begin
            result = (Sheety::Functions.average([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || ""), (Croupier::TaskManager.get("Sheet1!A3") || ""), (Croupier::TaskManager.get("Sheet1!A4") || ""), (Croupier::TaskManager.get("Sheet1!A5") || ""), (Croupier::TaskManager.get("Sheet1!A6") || ""), (Croupier::TaskManager.get("Sheet1!A7") || ""), (Croupier::TaskManager.get("Sheet1!A8") || ""), (Croupier::TaskManager.get("Sheet1!A9") || ""), (Croupier::TaskManager.get("Sheet1!A10") || ""), (Croupier::TaskManager.get("Sheet1!A11") || ""), (Croupier::TaskManager.get("Sheet1!A12") || ""), (Croupier::TaskManager.get("Sheet1!A13") || ""), (Croupier::TaskManager.get("Sheet1!A14") || ""), (Croupier::TaskManager.get("Sheet1!A15") || ""), (Croupier::TaskManager.get("Sheet1!A16") || ""), (Croupier::TaskManager.get("Sheet1!A17") || ""), (Croupier::TaskManager.get("Sheet1!A18") || ""), (Croupier::TaskManager.get("Sheet1!A19") || ""), (Croupier::TaskManager.get("Sheet1!A20") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet2_A2",
          inputs: ["kv://Sheet1!D3"],
          outputs: ["kv://Sheet2!A2"],
        ) do
          begin
            result = (begin; ln = Sheety::Functions.to_float((Croupier::TaskManager.get("Sheet1!D3") || "")); rn = Sheety::Functions.to_float(2.0); (ln && rn) ? (ln * rn).to_s : nil; end)

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


        Croupier::Task.new(
          id: "formula_Sheet2_A3",
          inputs: ["kv://Sheet1!A1", "kv://Sheet1!A2"],
          outputs: ["kv://Sheet2!A3"],
        ) do
          begin
            result = (Sheety::Functions.sum([(Croupier::TaskManager.get("Sheet1!A1") || ""), (Croupier::TaskManager.get("Sheet1!A2") || "")]))

            # Convert result to string - this is what the task "outputs"
            case result
            when Float64
              if result == result.to_i
                result.to_i.to_s
              else
                result.to_s
              end
            when String
              result
            when Bool
              result.upcase.to_s
            when Sheety::Functions::ErrorValue
              result.to_s
            when Nil
              ""
            else
              result.to_s
            end
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end
        end
      


# Execute all tasks
puts "=== Executing Croupier Tasks ==="
Croupier::TaskManager.run_tasks

# Collect cell data for TUI
  sheet_Sheet1_data = [
            {cell: "B3", formula: "=CONCAT(B1,\" \",B2)", value: Croupier::TaskManager.get("Sheet1!B3") || ""},
          {cell: "C3", formula: "=IF(C1>C2,\"Yes\",\"No\")", value: Croupier::TaskManager.get("Sheet1!C3") || ""},
          {cell: "D1", formula: "=MAX(A1:A20)", value: Croupier::TaskManager.get("Sheet1!D1") || ""},
          {cell: "D2", formula: "=MIN(A1:A20)", value: Croupier::TaskManager.get("Sheet1!D2") || ""},
          {cell: "D3", formula: "=SUM(A1:A20)", value: Croupier::TaskManager.get("Sheet1!D3") || ""},
          {cell: "D4", formula: "=AVERAGE(A1:A20)", value: Croupier::TaskManager.get("Sheet1!D4") || ""},
          {cell: "A1", formula: "", value: Croupier::TaskManager.get("Sheet1!A1") || ""},
          {cell: "A2", formula: "", value: Croupier::TaskManager.get("Sheet1!A2") || ""},
          {cell: "A3", formula: "", value: Croupier::TaskManager.get("Sheet1!A3") || ""},
          {cell: "A4", formula: "", value: Croupier::TaskManager.get("Sheet1!A4") || ""},
          {cell: "B1", formula: "", value: Croupier::TaskManager.get("Sheet1!B1") || ""},
          {cell: "B2", formula: "", value: Croupier::TaskManager.get("Sheet1!B2") || ""},
          {cell: "C1", formula: "", value: Croupier::TaskManager.get("Sheet1!C1") || ""},
          {cell: "C2", formula: "", value: Croupier::TaskManager.get("Sheet1!C2") || ""}
          ]

  sheet_Sheet2_data = [
            {cell: "A2", formula: "=Sheet1!D3*2", value: Croupier::TaskManager.get("Sheet2!A2") || ""},
          {cell: "A3", formula: "=SUM(Sheet1!A1:A2)", value: Croupier::TaskManager.get("Sheet2!A3") || ""},
          {cell: "A1", formula: "", value: Croupier::TaskManager.get("Sheet2!A1") || ""}
          ]

# Build sheets array and data hash
sheets = ["Sheet1", "Sheet2"]
sheet_data = {
    "Sheet1" => sheet_Sheet1_data,
    "Sheet2" => sheet_Sheet2_data
  }

# Create TUI instance
tui = Sheety::TUI.new(sheets, sheet_data) do |sheet, cell_ref, new_value|
  # Update callback: called when user saves a cell edit
  full_key = sheet.empty? ? cell_ref : sheet + "!" + cell_ref

  # Update the value in Croupier store
  Croupier::TaskManager.set(full_key, new_value)

  # Re-run dependent tasks
  Croupier::TaskManager.run_tasks
end

# Set value getter callback to fetch fresh values from Croupier store
tui.set_value_getter do |sheet, cell_ref|
  full_key = sheet.empty? ? cell_ref : sheet + "!" + cell_ref
  Croupier::TaskManager.get(full_key) || ""
end

# Set refresh callback to refresh the grid after updates
tui.set_refresh_callback do
  tui.refresh_current_sheet
end

# Run the TUI
tui.run
