require "big"
require "croupier"
require "./ast"

module Sheety
  # Generates and registers Croupier tasks from Excel formulas
  class CroupierGenerator
    include AST

    # Structure to hold formula information
    struct FormulaInfo
      getter cell : String
      getter formula : String
      getter sheet : String?

      def initialize(@cell : String, @formula : String, @sheet : String? = nil)
      end

      def key : String
        @sheet ? "#{@sheet}!#{@cell.upcase}" : @cell.upcase
      end
    end

    # Result of source generation: the entrypoint source plus any auxiliary
    # chunk files (filename => content) the entrypoint requires. aux_files is
    # empty for small sheets; for large sheets the task table is split across
    # chunk files to keep the Crystal compiler's peak memory low.
    struct GeneratedSource
      getter entrypoint : String
      getter aux_files : Hash(String, String)
      getter? split : Bool

      def initialize(@entrypoint : String, @aux_files : Hash(String, String) = Hash(String, String).new, @split : Bool = false)
      end
    end

    # Above this many formula cells, split the task table across chunk files so
    # the compiler stays within modest memory. Measured: chunk size 500 caps
    # peak RSS at ~1.5GB for a 9900-cell sheet (vs ~13.8GB single-file).
    SPLIT_THRESHOLD = 500
    CHUNK_SIZE      = 500

    @formulas : Hash(String, FormulaInfo)
    @generator : CodeGenerator
    @extractor : DependencyExtractor
    @state_file_path : String?
    @kv_store_path : String?
    @spreadsheet_uuid : String?
    @original_filename : String?
    # Maps FormulaInfo#key -> index of its shared calc_shape_N helper.
    # Built once per generate_source call; nil outside that scope.
    @shape_assignment : Hash(String, Int32)?

    def initialize
      @formulas = Hash(String, FormulaInfo).new
      @generator = CodeGenerator.new
      @extractor = DependencyExtractor.new
      @state_file_path = nil
      @kv_store_path = nil
      @spreadsheet_uuid = nil
      @original_filename = nil
      @shape_assignment = nil
    end

    # Set the original filename (for save functionality)
    def set_original_filename(filename : String) : self
      @original_filename = filename
      self
    end

    # Set the path for the .croupier state file
    def set_state_file_path(path : String) : self
      @state_file_path = path
      self
    end

    # Set the path for the persistent k/v store
    def set_kv_store_path(path : String) : self
      @kv_store_path = path
      self
    end

    # Set the spreadsheet UUID (for tracking purposes)
    def set_spreadsheet_uuid(uuid : String) : self
      @spreadsheet_uuid = uuid
      self
    end

    # Add a formula to be converted to a task
    def add_formula(cell : String, formula : String, sheet : String? = nil) : self
      # Store formula as-is (we'll strip '=' when parsing)
      key = sheet ? "#{sheet}!#{cell}" : cell

      @formulas[key] = FormulaInfo.new(cell, formula, sheet)
      self
    end

    # Parse formula string and validate it
    private def parse_formula(formula : String) : Node?
      _, builder = Parser.new.ast(formula)
      builder.root
    rescue e : FormulaError
      nil
    end

    # Sanitize key for use in task ID
    private def sanitize_key(key : String) : String
      key.gsub(/[!\/]/, "_")
    end

    # Generate Crystal source code for all tasks.
    # Returns a GeneratedSource: the entrypoint program plus, for large sheets,
    # auxiliary chunk files the entrypoint requires. Callers write the entrypoint
    # to their chosen path and the aux files into the same directory.
    # `chunk_prefix` names the chunk files (e.g. "abc123" -> "abc123_tasks_0.cr")
    # so sheets sharing a tmp dir don't collide; required only when splitting.
    def generate_source(initial_values : Hash(String, BigFloat | String | Bool) = Hash(String, BigFloat | String | Bool).new, interactive : Bool = false, source_file : String? = nil, intermediate_file : String? = nil, chunk_prefix : String = "sheety") : GeneratedSource
      if interactive
        # For interactive mode, require termisu instead of tablo
        source = %{
          require "croupier"
          require "termisu"
          require "../src/sheety/tui"
          require "../src/sheety/functions/registry"
          require "../src/sheety/croupier_helpers"

          # Auto-generated Excel formula tasks for Croupier
          # Generated by Sheety

        }
      else
        source = %{
          require "croupier"
          require "tablo"
          require "../src/sheety/functions/registry"
          require "../src/sheety/croupier_helpers"

          # Auto-generated Excel formula tasks for Croupier
          # Generated by Sheety

        }
      end

      # First add setup code (initial values)
      source += generate_setup_code(initial_values)
      source += "\n\n"

      # Ensure directories exist for state files
      if @state_file_path || @kv_store_path
        source += "# Ensure parent directories exist for state files\n"
        if @state_file_path
          source += "state_dir = File.dirname(#{@state_file_path.inspect})\n"
          source += "Dir.mkdir_p(state_dir) unless Dir.exists?(state_dir)\n"
        end
        if @kv_store_path
          source += "Dir.mkdir_p(#{@kv_store_path.inspect}) unless Dir.exists?(#{@kv_store_path.inspect})\n"
        end
        source += "\n"
      end

      # Configure state file path if set
      if @state_file_path
        source += "# Configure Croupier state file path\n"
        source += "Croupier::TaskManager.state_file = #{@state_file_path.inspect}\n\n"
      end

      # Configure persistent k/v store if set
      if @kv_store_path
        source += "# Configure persistent k/v store for caching results across runs\n"
        source += "Croupier::TaskManager.use_persistent_store(#{@kv_store_path.inspect})\n\n"
      end

      source += "\n"

      # Build shape assignment and emit one shared helper per unique formula
      # shape. Each parseable formula's task body becomes a call to its helper,
      # so a formula repeated across many cells only generates its calculation
      # logic once.
      source += generate_shape_helpers
      source += "\n\n"

      # Then register all formula tasks via a single data-driven loop (one
      # Croupier::Task.new call site) rather than a literal Task.new block per
      # cell. For large sheets the task table is split across chunk files to
      # keep the Crystal compiler's peak memory low.
      reg_entrypoint, aux_files, did_split = build_task_registration(chunk_prefix)
      source += reg_entrypoint
      source += "\n\n"

      # Finally, run the tasks and print results
      if interactive
        source += generate_tui_mode(initial_values, source_file, intermediate_file)
      else
        source += generate_execution_code(initial_values)
      end

      GeneratedSource.new(source, aux_files, did_split)
    end

    # Write a GeneratedSource to disk: the entrypoint to entrypoint_path, and
    # each aux file into the same directory. The four crystal-build call sites
    # then compile just the entrypoint (which requires its sibling chunks).
    def self.write_generated(gen : GeneratedSource, entrypoint_path : String) : Nil
      File.write(entrypoint_path, gen.entrypoint)
      dir = File.dirname(entrypoint_path)
      gen.aux_files.each do |name, content|
        File.write(File.join(dir, name), content)
      end
    end

    # Generate code to set initial values
    private def generate_setup_code(initial_values : Hash(String, BigFloat | String | Bool)) : String
      # Collect all unique ranges from formulas
      ranges = Set(NamedTuple(sheet: String, start_col: String, start_row: Int32, end_col: String, end_row: Int32)).new

      @formulas.each do |_, info|
        formula = info.formula.starts_with?("=") ? info.formula : "=#{info.formula}"
        ast = parse_formula(formula)
        next if ast.nil?

        # Extract dependencies including expanded ranges
        dependencies = @extractor.extract(ast, info.sheet)
        dependencies.each do |_|
          # Check if this dependency is a range reference by looking for patterns
          # We need to find the original range references in the AST
        end

        # Find range references directly in the calc code
        calc_code = @generator.generate(ast, CodeGenerator::Context.new(info.sheet))
        if calc_code.includes?("fetch_cell_range") # also matches fetch_cell_range_2d
          # Extract all range parameters (not just the first one); both
          # helpers take identical arguments, so one pattern covers them.
          calc_code.scan(/fetch_cell_range(?:_2d)?\("([^"]+)", "([A-Z]+)", (\d+), "([A-Z]+)", (\d+)\)/) do |match|
            ranges << {
              sheet:     match[1],
              start_col: match[2],
              start_row: match[3].to_i,
              end_col:   match[4],
              end_row:   match[5].to_i,
            }
          end
        end
      end

      # Build a hash of only the cells with actual values
      all_cells = Hash(String, String).new

      # Add user-provided values
      initial_values.each do |key, value|
        value_str = case value
                    when BigFloat then value.to_s
                    when String   then value
                    when Bool     then value.to_s
                    else               ""
                    end
        all_cells[key] = value_str
      end

      # Build setup code
      setup = ""

      # First, initialize all ranges to empty strings (required by Croupier)
      ranges.each do |range|
        setup += %{
initialize_range(#{range[:sheet].inspect}, #{range[:start_col].inspect}, #{range[:start_row]}, #{range[:end_col].inspect}, #{range[:end_row]})
}
      end

      # Then, set the cells with actual values
      unless all_cells.empty?
        setup += %{
# Set initial cell values
initialize_cells(#{all_cells.inspect})

}
      end

      setup
    end

    # Generate code to execute tasks and print results
    private def generate_execution_code(initial_values : Hash(String, BigFloat | String | Bool)) : String
      # Group cells by sheet and organize in grid
      sheets_data = {} of String => Hash(String, Hash(String, String))

      # Add formula cells
      @formulas.each do |key, info|
        parts = key.split("!", 2)
        sheet = parts.size > 1 ? parts[0] : "" # Use empty string for default sheet
        cell = parts.size > 1 ? parts[1] : parts[0]

        sheets_data[sheet] ||= Hash(String, Hash(String, String)).new
        sheets_data[sheet][cell] = {"formula" => info.formula}
      end

      # Add initial value cells (that don't have formulas)
      initial_values.each do |key, _|
        parts = key.split("!", 2)
        sheet = parts.size > 1 ? parts[0] : ""
        cell = parts.size > 1 ? parts[1] : parts[0]

        sheets_data[sheet] ||= Hash(String, Hash(String, String)).new
        # Only add if there's no formula already
        unless sheets_data[sheet][cell]?
          sheets_data[sheet][cell] = {"formula" => ""}
        end
      end

      # Generate code to collect all cell data per sheet. Each sheet's data is
      # built with << appends rather than a single large array literal, so the
      # compiler lowers N cheap append calls instead of one N-element literal.
      sheet_collection_code = sheets_data.map do |sheet, cells|
        sheet_display_name = sheet.empty? ? "(default)" : sheet
        sheet_var_name = sheet.empty? ? "default" : sheet.gsub(/[^a-zA-Z0-9]/, "_")
        sheet_key_prefix = sheet.empty? ? "" : "#{sheet}!"

        appends = cells.map do |cell, data|
          %(  sheet_#{sheet_var_name}_data << {cell: #{cell.inspect}, formula: #{data["formula"].inspect}, value: Croupier::TaskManager.get("#{sheet_key_prefix}#{cell}") || "(empty)"})
        end.join("\n")

        "  # Sheet: #{sheet_display_name}
  sheet_#{sheet_var_name}_data = [] of NamedTuple(cell: String, formula: String, value: String)
#{appends}"
      end.join("\n\n")

      sheet_print_code = sheets_data.keys.sort!.map do |sheet|
        sheet_var_name = sheet.empty? ? "default" : sheet.gsub(/[^a-zA-Z0-9]/, "_")
        sheet_display_name = sheet.empty? ? "(default)" : sheet
        "  print_sheet(sheet_#{sheet_var_name}_data, #{sheet_display_name.inspect})"
      end.join("\n")

      # Generate code to display results in a sheet layout
      %{
# Execute all tasks
puts "=== Executing Croupier Tasks ==="
Croupier::TaskManager.run_tasks

# Display results as sheets
puts ""
puts "=== Spreadsheet Results ==="
puts ""

#{sheet_collection_code}

# Helper functions are provided by Sheety::CellRefs (required via
# croupier_helpers) for column letter <-> number conversion.

def print_sheet(data, sheet_name)
  # Find the grid dimensions
  max_col = 0
  max_row = 0

  data.each do |cell|
    if match = cell[:cell].match(/^([A-Z]+)(\\d+)$/)
      col = match[1]
      row = match[2].to_i

      # Convert column to number for comparison
      col_num = Sheety::CellRefs.col_to_num(col)

      max_col = col_num if col_num > max_col
      max_row = row if row > max_row
    end
  end

  # Create a 2D grid
  grid = Array.new(max_row) { Array.new(max_col, "") }

  # Fill the grid
  data.each do |cell|
    if match = cell[:cell].match(/^([A-Z]+)(\\d+)$/)
      col = match[1]
      row = match[2].to_i - 1  # Convert to 0-indexed

      # Convert column to number
      col_num = Sheety::CellRefs.col_to_num(col)

      value = cell[:value]
      formula = cell[:formula]

      # Display: if there's a formula, show it, otherwise just the value
      display = formula.empty? ? value : formula + " -> " + value

      grid[row][col_num - 1] = display
    end
  end

  # Build column headers (A, B, C, ...)
  column_headers = (1..max_col).map { |i| Sheety::CellRefs.num_to_col(i) }

  # Build table data with row numbers
  table_data = (0...max_row).map do |row_idx|
    [row_idx + 1] + grid[row_idx]
  end

  # Create and print the table using Tablo
  table = Tablo::Table.new(table_data) do |t|
    t.add_column("Row", &.[](0).to_s)
    (1..max_col).each do |col_idx|
      t.add_column(column_headers[col_idx - 1], &.[](col_idx).to_s)
    end
  end

  puts table
  puts ""
end

#{sheet_print_code}
puts ""
}
    end

    # Group all parseable formulas by structural shape and emit one
    # `calc_shape_N(...)` helper per unique shape. Populates @shape_assignment
    # so generate_single_task_source can look up each formula's helper index.
    # Formulas that fail to parse are skipped here (they keep their inline
    # #VALUE! body) and are absent from @shape_assignment.
    private def generate_shape_helpers : String
      assignment = Hash(String, Int32).new
      # Ordered map: shape key -> {first ast, first sheet, param list, count}.
      shapes = [] of {key: String, ast: AST::Node, sheet: String?, params: Array(CodeGenerator::ReferenceParam)}

      @formulas.each do |_, info|
        formula = info.formula.starts_with?("=") ? info.formula : "=#{info.formula}"
        ast = parse_formula(formula)
        next if ast.nil?

        shape_key = @generator.shape_key(ast)
        existing = shapes.index { |entry| entry[:key] == shape_key }
        if existing
          assignment[info.key] = existing
        else
          params = @generator.reference_params(ast, info.sheet)
          shapes << {key: shape_key, ast: ast, sheet: info.sheet, params: params}
          assignment[info.key] = shapes.size - 1
        end
      end

      @shape_assignment = assignment

      return "" if shapes.empty?

      helpers = String.build do |io|
        io << "# Shared calculation helpers (one per unique formula shape)\n"
        shapes.each_with_index do |entry, index|
          params_decls = entry[:params].each_index.map do |param_index|
            @generator.param_declaration(entry[:params][param_index], param_index)
          end.join(", ")
          # Prefer the param declarations if there are any; otherwise use an
          # empty argument list (a no-arg formula like =42).
          signature = params_decls.empty? ? "" : "(#{params_decls})"
          param_body = @generator.generate_parameterized(entry[:ast], entry[:sheet])

          io << %(# Shape #{index}\n)
          io << %(def calc_shape_#{index}#{signature}\n)
          io << %(  begin\n)
          io << %(    result = (#{param_body})\n)
          io << %(    format_result(result)\n)
          io << %(  rescue e : Exception\n)
          io << %(    "#ERROR: " + (e.message || "Unknown error")\n)
          io << %(  end\n)
          io << %(end\n\n)
        end
      end

      # Trim trailing blank line; caller adds its own spacing.
      helpers.rstrip('\n') + "\n"
    end

    # Build the task-registration section. Returns a triple:
    #   {entrypoint_fragment, aux_files, did_split}
    # For small sheets (<= SPLIT_THRESHOLD formulas) the fragment is the full
    # inline table + loop and aux_files is empty. For large sheets the table is
    # partitioned into chunk files (one TASKS_N = [...] constant each), the
    # fragment requires them and concatenates their constants, and aux_files
    # maps each chunk filename to its content. Either way there is exactly one
    # register_formula_task (and thus one Croupier::Task.new) call site.
    private def build_task_registration(chunk_prefix : String) : {String, Hash(String, String), Bool}
      entries = @formulas.map { |_, info| task_entry_source(info) }

      return {"", Hash(String, String).new, false} if entries.empty?

      loop_body = String.build do |io|
        io << "formula_tasks.each do |task|\n"
        io << "  register_formula_task(task[:id], task[:inputs].call, task[:output], &task[:body])\n"
        io << "end\n"
      end

      # Small sheet: inline the whole table in the entrypoint.
      unless @formulas.size > SPLIT_THRESHOLD
        fragment = String.build do |io|
          io << "# Formula task registration (data-driven loop)\n"
          io << "formula_tasks = [\n"
          entries.each { |entry| io << entry }
          io << "]\n"
          io << loop_body
        end
        return {fragment, Hash(String, String).new, false}
      end

      # Large sheet: split the table across chunk files. Each chunk defines a
      # module-level TASKS_N constant; the entrypoint requires them and
      # concatenates into formula_tasks. Splitting lets the compiler retire
      # per-file structures during semantic analysis, capping peak memory.
      aux_files = Hash(String, String).new
      requires = [] of String
      concats = [] of String

      entries.each_slice(CHUNK_SIZE).with_index do |slice, index|
        filename = "#{chunk_prefix}_tasks_#{index}.cr"
        aux_files[filename] = String.build do |io|
          io << "TASKS_#{index} = [\n"
          slice.each { |entry| io << entry }
          io << "]\n"
        end
        requires << %(require "./#{chunk_prefix}_tasks_#{index}")
        concats << %(formula_tasks.concat(TASKS_#{index}))
      end

      fragment = String.build do |io|
        io << "# Formula task registration (data-driven loop, split across #{aux_files.size} chunk files)\n"
        io << "formula_tasks = [] of NamedTuple(id: String, inputs: Proc(Array(String)), output: String, body: Proc(String))\n"
        requires.each { |require_line| io << require_line << "\n" }
        concats.each { |concat_line| io << concat_line << "\n" }
        io << loop_body
      end
      {fragment, aux_files, true}
    end

    # Build the source for one entry in the formula_tasks table. Mirrors the
    # id/inputs/outputs/body derivation that previously lived in the per-cell
    # literal block, so runtime behavior is unchanged.
    private def task_entry_source(info : FormulaInfo) : String
      id = "formula_#{sanitize_key(info.key)}"
      output = "kv://#{info.key}"

      formula = info.formula.starts_with?("=") ? info.formula : "=#{info.formula}"
      ast = parse_formula(formula)

      if ast.nil?
        # Invalid formula: empty inputs, #VALUE! body.
        return %(  {id: #{id.inspect}, inputs: ->{ [] of String }, output: #{output.inspect}, body: ->{ "#VALUE!" }},\n)
      end

      # Extract dependencies - these are the inputs
      dependencies = @extractor.extract(ast, info.sheet)

      # Generate the concrete calculation code. Used to derive inputs (by
      # scanning for fetch_cell_range calls) and as the fallback body.
      calc_code = @generator.generate(ast, CodeGenerator::Context.new(info.sheet))

      # Build the inputs array expression - use range helpers when ranges appear
      # (both fetch_cell_range and fetch_cell_range_2d share the same argument
      # list, so one pattern catches either helper)
      range_matches = calc_code.scan(/fetch_cell_range(?:_2d)?\(([^)]+)\)/).map(&.[1])

      inputs_expr = if !range_matches.empty?
                      # Multiple ranges - combine them with + operator
                      range_inputs_calls = range_matches.map { |range_params| "range_inputs(#{range_params})" }
                      range_inputs_calls.join(" + ")
                    elsif dependencies.empty?
                      "[] of String"
                    else
                      "[" + dependencies.map { |dep| "\"kv://#{dep}\"" }.join(", ") + "] of String"
                    end

      # Body: if this formula shares a calc_shape_N helper, call it with the
      # concrete fetch expressions for this cell's reference leaves. Otherwise
      # fall back to the inline calculation.
      body_expr = if (assignment = @shape_assignment) && (index = assignment[info.key]?)
                    call_args = @generator.reference_params(ast, info.sheet).map { |param| @generator.fetch_expression_for(param) }
                    "calc_shape_#{index}(#{call_args.join(", ")})"
                  else
                    %(begin
            result = (#{calc_code})
            format_result(result)
          rescue e : Exception
            "#ERROR: " + (e.message || "Unknown error")
          end)
                  end

      %(  {id: #{id.inspect}, inputs: ->{ #{inputs_expr} }, output: #{output.inspect}, body: ->{ #{body_expr} }},\n)
    end

    # Generate TUI mode
    private def generate_tui_mode(initial_values : Hash(String, BigFloat | String | Bool), source_file : String?, intermediate_file : String?) : String
      # Get the sheet data collection code
      sheets_data = {} of String => Hash(String, Hash(String, String))

      @formulas.each do |key, info|
        parts = key.split("!", 2)
        sheet = parts.size > 1 ? parts[0] : ""
        cell = parts.size > 1 ? parts[1] : parts[0]

        sheets_data[sheet] ||= Hash(String, Hash(String, String)).new
        sheets_data[sheet][cell] = {"formula" => info.formula}
      end

      initial_values.each do |key, _|
        parts = key.split("!", 2)
        sheet = parts.size > 1 ? parts[0] : ""
        cell = parts.size > 1 ? parts[1] : parts[0]

        sheets_data[sheet] ||= Hash(String, Hash(String, String)).new
        unless sheets_data[sheet][cell]?
          sheets_data[sheet][cell] = {"formula" => ""}
        end
      end

      # Generate code to collect all cell data per sheet. Built with << appends
      # rather than a single large array literal, to keep compile-time memory
      # low on big sheets (matches the batch-mode collection form).
      sheet_collection_code = sheets_data.map do |sheet, cells|
        sheet_var_name = sheet.empty? ? "default" : sheet.gsub(/[^a-zA-Z0-9]/, "_")
        sheet_key_prefix = sheet.empty? ? "" : "#{sheet}!"

        appends = cells.map do |cell, data|
          %(  sheet_#{sheet_var_name}_data << {cell: #{cell.inspect}, formula: #{data["formula"].inspect}, value: fetch_cell("#{sheet_key_prefix}#{cell}")})
        end.join("\n")

        "  sheet_#{sheet_var_name}_data = [] of NamedTuple(cell: String, formula: String, value: String)
#{appends}"
      end.join("\n\n")

      # Build the sheets array and data hash
      sheets_array = sheets_data.keys.sort!.map do |sheet|
        sheet.inspect
      end.join(", ")

      sheets_data_init = sheets_data.keys.sort!.map do |sheet|
        sheet_var_name = sheet.empty? ? "default" : sheet.gsub(/[^a-zA-Z0-9]/, "_")
        "#{sheet.inspect} => sheet_#{sheet_var_name}_data"
      end.join(",\n    ")

      %{
# Execute all tasks
puts "=== Executing Croupier Tasks ==="
Croupier::TaskManager.run_tasks

# Collect cell data for TUI
#{sheet_collection_code}

# Build sheets array and data hash
sheets = [#{sheets_array}]
sheet_data = {
    #{sheets_data_init}
  }

# Create TUI instance
tui = Sheety::TUI.new(sheets, sheet_data) do |sheet, cell_ref, new_value|
  # Update callback: called when user saves a cell edit
  full_key = sheet.empty? ? cell_ref : sheet + "!" + cell_ref

  # Update the value in Croupier store
  Croupier::TaskManager.set(full_key, new_value)

  # Re-run dependent tasks
  Croupier::TaskManager.run_tasks
end

# Set source file for save functionality
#{source_file ? "tui.set_source_file(#{source_file.inspect})" : ""}

# Set original source file for saves (persists across rebuilds)
#{@original_filename ? "tui.set_original_source_file(#{@original_filename.inspect})" : (source_file ? "tui.set_original_source_file(#{source_file.inspect})" : "")}

# Set intermediate file for auto-saves (formula edits)
#{intermediate_file ? "tui.set_intermediate_file(#{intermediate_file.inspect})" : ""}

# Set value getter callback to fetch fresh values from Croupier store
tui.set_value_getter do |sheet, cell_ref|
  fetch_cell(sheet.empty? ? cell_ref : sheet + "!" + cell_ref)
end

# Set refresh callback to refresh the grid after updates
tui.set_refresh_callback do
  tui.refresh_current_sheet
end

# Restore UI state if available
#{source_file ? %{
# Try to restore cursor position from YAML
begin
  yaml_data = YAML.parse(File.read(#{source_file.inspect}))
  if yaml_data.as_h.has_key?("_ui_state")
    ui_state = yaml_data["_ui_state"]
    if ui_state.as_h.has_key?("active_sheet") && ui_state.as_h.has_key?("active_cell")
      saved_sheet = ui_state["active_sheet"].as_s
      saved_cell = ui_state["active_cell"].as_s
      tui.set_initial_position(saved_sheet, saved_cell)
    end
  end
rescue
  # Ignore errors restoring UI state
end
} : ""}

# Run the TUI
tui.run
}
    end
  end
end
